### ISSUE TITLE
build with cmake 3.16.6 vs 2019

### ISSUE THREAD

**Issue by EricDDK** [Ubpa/UECS#2]
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FetchContent.cmake:915 (message):
  Build step for ucontainer failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FetchContent.cmake:1006 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FetchContent.cmake:1047 (FetchContent_Populate)
  build/_deps/ucmake-src/cmake/UbpaPackage.cmake:78 (FetchContent_MakeAvailable)
  build/_deps/ucmake-src/cmake/UbpaPackage.cmake:85 (Ubpa_AddDepPro)
  CMakeLists.txt:11 (Ubpa_AddDep)

**Comment by Ubpa** [comment]
Sorry, I forgot to tag [UContainer](https://github.com/Ubpa/UContainer) 0.0.6.
I fixed it. Now, you can try again.

**Comment by EricDDK** [comment]
> Sorry, I forgot to tag [UContainer](https://github.com/Ubpa/UContainer) 0.0.6.
> I fixed it. Now, you can try again.

Thanks, its okay
