### ISSUE TITLE
compile error on MacOS, gcc10.2

### ISSUE THREAD

**Issue by JohnYoung404** [Ubpa/UECS#3]
<img width="995" alt="screenshot" src="https://user-images.githubusercontent.com/12005212/107171211-31ea1980-69fd-11eb-9ae3-46a375900692.png">
hi~ I got a compile error on MacOS, Cmake 3.17, gcc 10.2.
C++20 features make it hard to be crossplatformed :D

**Comment by Ubpa** [comment]
I just test the code on Win10 & Ubuntu. I'll test it on MacOS sometime in the future.

**Comment by JohnYoung404** [comment]
thanks a lot! 
It's too hard for me to fix it~ but I really want to integrate your amazing job on multiple platforms :D

**Comment by Ubpa** [comment]
I fix the bug in [UTemplate](https://github.com/ubpa/UTemplate). Later I will update in UECS.
On MacOs, std::size_t == unsigned long, and it is different from std::uint64_t == unsigned long long. But on other platforms, std::size_t == std::uint64_t == unsigned long long.

**Comment by Ubpa** [comment]
I fix the bugs, please checkout [0.15.1](https://github.com/Ubpa/UECS/tree/0.15.1).
