### ISSUE TITLE
Possible problems

### ISSUE THREAD

**Issue by ShenMian** [Ubpa/UECS#4]
1. 请问是否可能存在 `entityTableFreeEntry.size()` 大于 `entityTable.size()` 的情况?
比如: 先创建几个实体, 然后将他们全部销毁, 最后调用 `EntityMngr::TotalEntityNum()` 试图获取实体数量.
https://github.com/Ubpa/UECS/blob/8973492619443785cccc5a794ba47c437a51db34/include/UECS/EntityMngr.hpp#L66

2. 请问 `e.index` 是否可能在 `EntityMngr::entityTableFreeEntry` 中呢?
https://github.com/Ubpa/UECS/blob/8973492619443785cccc5a794ba47c437a51db34/src/core/EntityMngr.cpp#L82

因为没有完整的阅读源码, 若我有地方没注意到请见谅.

**Comment by Ubpa** [comment]
1. 不会
2. 可能：当 e 是存活的，e 不在 free 中，当 e 是销毁的，e 在 free 中
entityTable 是一个容器，里边的entity可能为空，空的部分记录在 entityTableFreeEntry 里，用于后续的分配

**Comment by ShenMian** [comment]
1. 请问为什么不会, 是有代码可以确保 `entityTableFreeEntry` 中的元素小于 `entityTable.size()` 或其他解决方案吗?
2. 这里是因为 `e.index` 在 `entityTableFreeEntry` 中的话 `e.version` 一定不会和 `entityTable[e.index].version` 相等所以不需要进一步判断 `e.index` 是否在 `entityTableFreeEntry` 中, 是吗?

**Comment by Ubpa** [comment]
1. `entityTableFreeEntry` 是用于记录 `entityTable` 中为空的索引，从逻辑上显然就是 `entityTableFreeEntry.size()` 会小于 `entityTable.size()`
2. 是的

**Comment by ShenMian** [comment]
每次调用 `EntityMngr::Destory` 时一定会压入一个被回收的索引, 但是调用 `EntityMngr::Create` 有可能会弹出一个索引. 如果是这样的话 `EntityMngr::entityTableFreeEntry.size()` 好像可能一直变大直至超过 `EntityMngr::entityTable.size()`?
```cpp
EntityMngr mgr;
auto e = mgr.Create(...); // entityTable.size() == 1, entityTableFreeEntry == 0
mgr.Destory(e);           // entityTable.size() == 0, entityTableFreeEntry == 1
mgr.TotalEntityNum();
```

**Comment by Ubpa** [comment]
```c++
EntityMngr mgr;
auto e = mgr.Create(...); // entityTable.size() == 1, entityTableFreeEntry == 0
mgr.Destory(e);           // entityTable.size() == **1**, entityTableFreeEntry == 1
mgr.TotalEntityNum();
```

**Comment by ShenMian** [comment]
明白了, 谢谢.
