### ISSUE TITLE
I have red some of UECS, there is a issue

### ISSUE THREAD

**Issue by wiltchamberian** [Ubpa/UECS#5]
Chunk.cpp   69   std::size_t Chunk::Erase(std::size_t idx)

movedEntityIdx = reinterpret_cast<Entity*>(dstBuffer + head->GetCmptInfos()[entityTypeIdx].offset + sizeof(Entity) * srcIdxInChunk)->index;

the  sizeof(Entity),  I think it may something like sizeof(tagSize), for 
I think you put the Entity as a component with its compoents , right?
But this is an old version, may be you have changed ,or something I understood wrong

**Comment by Ubpa** [comment]
Yes, `Entity` is a special component for an entity.
It can only be used inside the framework, and users are not supposed to access it.

**Comment by wiltchamberian** [comment]
I think you use a  SOA( structure of arrays) ,but I have a question ,for if a system should process more than one component at the same time
this will be better than the AOS of cpu cache? for example I have   Position Component and a Velocity component, i  should use position + velocity to update position

**Comment by Ubpa** [comment]
Yes, it's a cache locality problem.
Suppose you have an `Archetype` which has lots of component including `Position` and `Velocity`.
If entities store in chunk as SOA, the CPU cache only need to load `Position` array and `Velocity` array.
However, if entities store in chunk as AOS, the CPU cache need to load all data of entities, which is really slow.

**Comment by wiltchamberian** [comment]
um.... i got your meaning ,i red much of your ecs implement and for the part i have unserstood, i think your implement is very well

**Comment by wiltchamberian** [comment]
um.... i got your meaning ,i red much of your ecs implement and for the part i have unserstood, i think your implement is very well
