### ISSUE TITLE
erase the Entity, the chunk idx changed

### ISSUE THREAD

**Issue by wiltchamberian** [Ubpa/UECS#6]
Archetype.cpp   
std::size_t Archetype::Erase(EntityAddress addr) 
chunks.erase(std::find(chunks.begin(), chunks.end(), chunk)); 

you erase a vector, so the index of the elements after the iterator all changed;
but in entityTable  in EntityMngr, some may still ref to the old index , is this some bug?

**Comment by Ubpa** [comment]
I have fixed the bug at b98fa1c29ae693a39cf6b8f4a06877bf6410e08c (15 May 2021).
